version: '3.9'
name: branch-task-docker-db
services:
  postgres_db_service:
    container_name: postgres_local
    image: postgres:16
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=my-branch-task-db